---
name: Antithesis Verify Pipeline

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - 'tests/antithesis/**'
      - '.github/workflows/antithesis-verify.yml'
  pull_request:
    paths:
      - 'tests/antithesis/**'
      - '.github/workflows/antithesis-verify.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [docker, k8s]
    name: Test Antithesis ${{ matrix.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Build images
        run: |
          make -C tests/antithesis antithesis-build-${{ matrix.environment }}-config-image
          make -C tests/antithesis antithesis-build-etcd-image
          make -C tests/antithesis antithesis-build-client-image

      - name: Set up system
        working-directory: ./tests/antithesis
        run: |
          make antithesis-${{ matrix.environment }}-up &

      - name: Wait for healthy system
        working-directory: ./tests/antithesis
        run: |
          make antithesis-${{ matrix.environment }}-wait-healthy

      - name: Run traffic
        working-directory: ./tests/antithesis
        run: make antithesis-run-${{ matrix.environment }}-traffic

      - name: Run validation
        working-directory: ./tests/antithesis
        run: make antithesis-run-${{ matrix.environment }}-validation

      - name: Clean up
        if: always()
        working-directory: ./tests/antithesis
        run: make antithesis-${{ matrix.environment }}-clean
